services:
    app:
        container_name: laravel
        build:
            context: .
            dockerfile: Dockerfile
        image: php81
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - api-network
    nginx:
        container_name: nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - api-network

    mysql:
        image: mariadb
        container_name: mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./docker/database/mariadb:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - api-network


networks:
    api-network:
        driver: bridge
